# Generated by Django 2.2 on 2019-06-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('body', models.TextField(verbose_name='Noticia')),
                ('start_date', models.DateField(verbose_name='Fecha de comienzo')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('body', models.TextField(verbose_name='Noticia')),
                ('publish_date', models.DateField(auto_now=True, verbose_name='Fecha de publicación')),
                ('image', models.ImageField(default='djangoworld.png', upload_to='uploads/%Y/%m/%d/', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
