# Generated by Django 2.2 on 2019-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='media/djangoworld.png', upload_to='media/%Y/%m/%d/', verbose_name='Imagen'),
        ),
    ]
