# Generated by Django 2.2 on 2019-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190621_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default='media/djangoworld.png', null=True, upload_to='media', verbose_name='Imagen'),
        ),
    ]
