# Generated by Django 2.2 on 2019-06-21 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190621_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default='media/djangoworld.png', null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Imagen'),
        ),
    ]
