# Generated by Django 2.2 on 2019-06-22 15:07

import blog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190621_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, default='media/djangoworld.png', null=True, upload_to='media', validators=[blog.validators.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Imagen'),
        ),
    ]
